### ISSUE TITLE
Move annotations (or delete them) when text is changed

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-highlighter-ng#24]
annotations need to be moved when text is changed.
We might want to add an event listener, that listens on text saves here and fire the signals in the ontology models when needed.

Probably this code https://github.com/acdh-oeaw/apis-core/blob/main/apis_core/apis_metainfo/models.py#L387-L414
can be reused

**Comment by b1rger** [comment]
see also #20
